name: Run PR tests

on:
  pull_request:
    branches: [ master ]

jobs:
  run-pr-checks:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright
      options: --user 1001
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn check-format
    - name: Save/restore parcel build cache
      uses: actions/cache@v2
      with:
        key: parcel
        path: '.parcel'
    - run: yarn test
    - run: yarn build
